version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: live-polling-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: live-polling-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb+srv://irfanmohamed1182005_db_user:Irfan1123@polling.e6halcl.mongodb.net/?appName=Polling
      - MONGO_DB=livepolling
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super-secret-jwt-key-hcl-guvi-2026
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: live-polling-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  redis_data:
